'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
require('../js/architecture.js');require('../js/architecture-shaders.js');require('../js/geology.js');require('../js/geology-shaders.js');require('../js/shaders.js');
const N=globalThis.Noumen,root=path.resolve(__dirname,'..');
let geometry;
const structure=()=>geometry||(geometry=N.architecture.createGeometry());
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
test('VIGIL consists of substantial three-dimensional closed geometry',()=>{const g=structure();assert.equal(g.rings,2);assert.ok(g.modules>1000);assert.ok(g.vertices>100000);assert.equal(g.data.length,g.vertices*g.stride);assert.equal(g.vertices%3,0);assert.equal(g.stride,8);});
test('VIGIL geometry is finite, normalized and clear of the central planet',()=>{const g=structure();for(let i=0;i<g.data.length;i+=8){const v=g.data.subarray(i,i+8);assert.ok(v.every(Number.isFinite));const radius=Math.hypot(v[0],v[1],v[2]);assert.ok(radius>1.2&&radius<2.05);assert.ok(Math.abs(Math.hypot(v[3],v[4],v[5])-1)<.00001);}});
test('architecture provides separate shell, rail, radiator, aperture and light materials',()=>{const g=structure(),kinds=new Set();for(let i=6;i<g.data.length;i+=8){kinds.add(g.data[i]);assert.ok(g.data[i+1]>=0&&g.data[i+1]<1);}for(const k of [0,1,2,4,5,6])assert.ok(kinds.has(k));});
test('architecture generation is deterministic across fresh runs',()=>{const a=structure(),b=N.architecture.createGeometry();assert.equal(hash(Buffer.from(a.data.buffer)),hash(Buffer.from(b.data.buffer)));});
test('LACUNA icosphere subdivision preserves unit-radius manifold topology',()=>{for(let level=0;level<=3;level++){const {v,f}=N.geology.ico(level);assert.equal(f.length,20*4**level);assert.equal(v.length,10*4**level+2);for(const p of v)assert.ok(Math.abs(Math.hypot(...p)-1)<1e-10);const edges=new Map();for(const face of f)for(let i=0;i<3;i++){const [a,b]=[face[i],face[(i+1)%3]].sort((a,b)=>a-b);const k=a+','+b;edges.set(k,(edges.get(k)||0)+1);}assert.ok([...edges.values()].every(n=>n===2));}});
test('seeded geological noise is finite, bounded and continuous',()=>{for(let k=0;k<500;k++){const x=k*.0347,y=k*.078,z=-k*.057;const v=N.geology.noise(x,y,z);assert.ok(v>=-1&&v<=1);assert.ok(Math.abs(v-N.geology.noise(x+1e-6,y,z))<.0001);}});
test('VIGIL has a dedicated depth-tested geometry pass and an independent shadow pass',()=>{const s=fs.readFileSync(path.join(root,'js/renderer.js'),'utf8');for(const token of ['renderStructureShadow','architectureTarget','structureShadowTarget','structureBuffer','gl.DEPTH_TEST','uArchitectureRange'])assert.ok(s.includes(token),token);assert.ok(N.architectureShaders.shadowFragment.includes('65025.'));assert.ok(N.structureShadowGLSL.includes('step(depth-bias'));});
test('packed structure depth is sampled without illegal linear interpolation',()=>{const s=fs.readFileSync(path.join(root,'js/renderer.js'),'utf8');assert.match(s,/TEXTURE_MIN_FILTER,gl\.NEAREST/);assert.match(s,/TEXTURE_MAG_FILTER,gl\.NEAREST/);assert.match(N.structureShadowGLSL,/1\.\/65025\./);});
test('architecture and its cast shadow use the same light-space projection',()=>{const a=N.architectureShaders.shadowVertex,b=N.structureShadowGLSL;assert.match(a,/-\.596,\.604,\.529/);assert.match(b,/-\.596,\.604,\.529/);assert.match(a,/2\.05/);assert.match(b,/4\.10/);assert.match(a,/2\.40/);assert.match(b,/4\.80/);});
test('the main fragment shader stays within eight texture samplers',()=>{const names=[...N.shaders.fragment.matchAll(/uniform sampler2D\s+(\w+)/g)].map(m=>m[1]);assert.equal(new Set(names).size,names.length);assert.ok(names.length<=8);assert.ok(names.includes('uArchitecture'));assert.ok(names.includes('uStructureShadow'));});
test('all shaders contain fully expanded dependencies and increasing smoothstep edges',()=>{for(const code of [N.shaders.fragment,N.architectureShaders.fragment,N.architectureShaders.shadowVertex,N.architectureShaders.shadowFragment,N.geologyShaders.fragment,N.postShader]){assert.doesNotMatch(code,/\$\{|\bundefined\b/);for(const m of code.matchAll(/smoothstep\(\s*(-?[.\d]+)\s*,\s*(-?[.\d]+)\s*,/g))assert.ok(Number(m[1])<Number(m[2]),m[0]);}});
test('ORISON uses an oblate globe aligned to its rings and Beer-Lambert ring transmission',()=>{const f=N.shaders.fragment;assert.ok(f.includes('oblateHit('));assert.ok(f.includes('ringLocal(local)'));assert.ok(f.includes('ringOpticalDepth(rad)/max(abs(dn)'));assert.ok(f.includes('ringOpticalDepth(rr)/max(abs(denom)'));assert.ok(!f.includes('sin(rr*3900.'));});
test('VESPER and VIGIL have independent material maps rather than painted bright halos',()=>{const f=N.shaders.fragment;for(const token of ['atlas(tex,1.)','atlasNormal(normal,tex,5.','dielectricSpecular','structureVisibility(local,normal)'])assert.ok(f.includes(token),token);assert.ok(!f.includes('tint*glow*illumination*.27'));});
test('all requested static assets are present and safe local paths',()=>{const renderer=fs.readFileSync(path.join(root,'js/renderer.js'),'utf8');for(const m of renderer.matchAll(/\['([^']+\.(?:jpg|png))','u\w+',\d+\]/g)){assert.ok(!m[1].includes('/'));assert.ok(fs.statSync(path.join(root,'assets',m[1])).size>1000);}assert.ok(fs.existsSync(path.join(root,'assets','lacuna-height.png')));});
test('script execution order satisfies all renderer dependencies',()=>{const h=fs.readFileSync(path.join(root,'index.html'),'utf8');const files=[...h.matchAll(/<script defer src="\.\/js\/([^"/]+)"><\/script>/g)].map(m=>m[1]);for(const [a,b] of [['math.js','app.js'],['architecture-shaders.js','shaders.js'],['geology.js','renderer.js'],['geology-shaders.js','renderer.js'],['architecture.js','renderer.js'],['shaders.js','renderer.js'],['renderer.js','app.js']])assert.ok(files.indexOf(a)>=0&&files.indexOf(a)<files.indexOf(b),a+' before '+b);});
test('preview exporter executes scripts after the document and does not become a deployment dependency',()=>{const s=fs.readFileSync(path.join(root,'tools/make-preview.cjs'),'utf8');assert.ok(s.includes("html.replace('</body>',scripts.join"));assert.ok(!fs.existsSync(path.join(root,'package.json')));assert.ok(!fs.existsSync(path.join(root,'.github')));});

test('the previous LACUNA and GEMINA source materials are preserved byte for byte',()=>{const expected={"gemina-albedo.jpg": "3530ea8d4972321d0795fce55cf7029e4f0a5854fa0694e4a0012451c9069d21", "gemina-relief.png": "66986eacffcb99b1ac97b12d7da420cc11cccd2e375e8e1e33a1c1109277cf32", "gemina-clouds.jpg": "b887043d987b1041c6cb2aa60b1588452aca338ca8059d25a0ae7e7a12b070d0", "lacuna-albedo.jpg": "97e3af4beaf067525956346a6265ce75a82de1fa6aaf643b9a660976c4bbcc08", "lacuna-relief.png": "f1aa4df208c34cfa407e3d5671053cb5d0d353daaef4e6c639562bb6f1203f34", "lacuna-height.png": "b08e0e20b1ed4d5ab2a261e40ad2fdafa183fb10ea3d4dd697e02bfbfbaad0f9"};for(const [file,digest] of Object.entries(expected))assert.equal(hash(fs.readFileSync(path.join(root,'assets',file))),digest,file);});

test('context loss forgets invalid GPU handles without deleting them in a new context',()=>{
  require('../js/math.js');require('../js/renderer.js');
  const listeners={},gl={getParameter:()=>16,getExtension:()=>null};
  const canvas={getContext:()=>gl,addEventListener:(name,fn)=>{listeners[name]=fn;},removeEventListener:()=>{}};
  let notified=false,prevented=false;
  const renderer=new N.UniverseRenderer(canvas,{onContextLost:()=>{notified=true;}});
  renderer.textures=[{}];renderer.programs=[{}];renderer.main={};renderer.quad={};renderer.structureShadowTarget={};renderer.geometry={keep:true};renderer.structureGeometry={keep:true};
  listeners.webglcontextlost({preventDefault:()=>{prevented=true;}});
  assert.ok(prevented&&notified&&renderer.lost);
  assert.equal(renderer.textures.length,0);assert.equal(renderer.programs.length,0);
  for(const key of ['main','quad','structureShadowTarget'])assert.equal(renderer[key],null);
  assert.ok(renderer.geometry.keep&&renderer.structureGeometry.keep);
});
